apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-lb
spec:
  type: LoadBalancer
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
